# Generated by Django 6.0.1 on 2026-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color',
        ),
        migrations.RemoveField(
            model_name='note',
            name='pinned',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
